change  unit name
canonical/grafana-k8s-operator pull request #118
Opened 2022-09-05 10:33 UTC by beliaev-maksim

would it make sense to change a unitname according to the warning per https://github.com/canonical/operator/pull/822 ?

2022-09-05 23:42 UTC, sed-i reviewed
Hi @beliaev-maksim, thanks for the PR!
I still see other additional tests fail on my end.
Could you please (temporarily) add this change to reqs txt so we can have CI reflect it?
```diff
-ops
+git+https://github.com/canonical/operator#egg=ops
```

2022-09-06 08:07 UTC, beliaev-maksim commented
you mean integrations that are not part of tox?
![image](https://user-images.githubusercontent.com/51964909/188571923-cb20c42f-8fa0-431c-8ff4-05bfaeed56e8.png)


I ran tests on my fork, looks OK except libs check, but I assume because it is a fork
https://github.com/beliaev-maksim/grafana-k8s-operator/pull/1

2022-09-06 10:15 UTC, sed-i commented
I mean unit tests.
Can you please change `requirements.txt` so that `ops` is taken from gh instead of from pypi?
```diff
-ops
+git+https://github.com/canonical/operator#egg=ops
```

2022-09-06 10:18 UTC, beliaev-maksim commented
@sed-i 
it is in there:
![image](https://user-images.githubusercontent.com/51964909/188610463-ef3d9bca-b36f-4ed5-af85-145a2dcf4fbd.png)

or do you mean something else?

2022-09-06 10:18 UTC, sed-i commented
I mean unit tests.
Can you please change `requirements.txt` so that `ops` is taken from gh instead of from pypi?
```diff
-ops
+git+https://github.com/canonical/operator#egg=ops
```

2022-09-06 10:22 UTC, sed-i commented
Ok great, missed it.

2022-09-06 10:49 UTC, beliaev-maksim commented
@sed-i 
about "check libs". It looks like some issue in pipeline action itself.
even bumping it to stable via #119 get it failed.
credentials/secrets ?

2022-09-06 12:31 UTC, rbarry82 requested changes

2022-09-06 12:31 UTC, rbarry82 commented on tests/unit/test_charm.py
> +        self.harness.add_relation_unit(rel.id, "grafana-k8s/1")
This will cause inconsistencies.

2022-09-07 09:36 UTC, simskij commented
I'm happy to merge with check libs failing, if everything else is sorted out. I do, however, think Ryan is right and that we need to sort out [this](https://github.com/canonical/grafana-k8s-operator/pull/118#issuecomment-1238085615) first

2022-09-07 09:37 UTC, rbarry82 approved these changes

2022-09-07 09:38 UTC, rbarry82 commented
Raised on MM for ops to look at, and the follow-up which rationalizes things LGTM.

2022-09-07 09:45 UTC, simskij commented
Thanks again @beliaev-maksim! 🎉

2022-09-07 09:45 UTC, merged