add optional secureJsonData to grafana datasources
canonical/grafana-k8s-operator pull request #297
Opened 2024-02-06 13:14 UTC by lucabello

## Issue
Some datasources, like Mimir, need custom HTTP Headers to be specified in the datasource configuration. 

As seen [here](https://grafana.com/docs/grafana/latest/administration/provisioning/#custom-http-headers-for-data-sources), header names can be specified under `jsonData`, which we currently build from the `extra_data` parameter in the `GrafanaSourceProvider` constructor.

However, the value for a header must be specified under `secureJsonData`, which we currently don't allow to specify in the `grafana_source` library.

## Solution
This PR adds an optional `secure_extra_data` constructor argument, right next to `extra_data`, so that we can (in the same fashion as `jsonData`) specify `secureJsonData` for a datasource.

2024-02-06 13:44 UTC, lucabello commented
Headers are set successfully now:
![Screenshot_20240206_144103](https://github.com/canonical/grafana-k8s-operator/assets/36242061/c7aae85e-f4be-421a-b45e-b50491d361bc)

And the Mimir datasource is happy as a consequence:
![Screenshot_20240206_144037](https://github.com/canonical/grafana-k8s-operator/assets/36242061/72dc0418-33b1-403e-924d-451231fa4377)

2024-02-08 09:10 UTC, PietroPasotti requested changes

2024-02-08 09:10 UTC, PietroPasotti commented on lib/charms/grafana_k8s/v0/grafana_source.py
> +    `extra_fields`: None
I'd like to see in the doc what these are for / what they map to, in terms of datasource config

2024-02-08 09:10 UTC, PietroPasotti commented on src/charm.py
> +                source["secureJsonData"] = source_info.get("secure_extra_fields")
(not something you NEED to fix in this PR unless you agree we should rename both vars, but maybe let's put a wishlist/todo for it?)

2024-02-14 12:38 UTC, lucabello commented on src/charm.py
> +                source["secureJsonData"] = source_info.get("secure_extra_fields")
I have no idea why that was the case :) I'll open a new issue to refactor it to be more clear!

2024-02-14 12:40 UTC, lucabello commented on lib/charms/grafana_k8s/v0/grafana_source.py
> +    `extra_fields`: None
It's already in the class documentation; this part of the docs only specifies the default argument (note how that's true for all others except `refresh_event`)

2024-02-14 13:33 UTC, PietroPasotti approved these changes
looks grafana to me

2024-02-15 10:17 UTC, merged