Self monitoring
canonical/grafana-k8s-operator pull request #50
Opened 2022-01-12 00:04 UTC by rbarry82

Add alertmanager rules, and send the metrics (already enabled out of the box) back to Prometheus so the alerts can actually fire.

Grafana includes a dashboard for itself which we can use.

2022-01-12 04:17 UTC, sed-i approved these changes
I wonder if self monitoring would have a noticeable impact on the load test / dcatasheet.

2022-01-12 04:17 UTC, sed-i commented on tox.ini
> +    mypy {[vars]all_path} {posargs} --exclude {[vars]tst_path}integration
I made changes to this file. Have you rebased?
https://github.com/canonical/grafana-k8s-operator/pull/49/files#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449

I think the `/` needs to stay because I removed it from the definition of tst_path.

2022-01-12 10:45 UTC, mmanciop commented on metadata.yaml
> +  metrics-endpoint:
I am thinking that, due to the nature of our charms being themselves monitoring tools, we need to put extra care in the naming, and probably break convention. We must have a discussion in the team about how to name these. cc @simskij

2022-01-12 10:46 UTC, mmanciop commented on src/prometheus_alert_rules/unit_unavailable.rule
> +expr: up{%%juju_topology%%} < 1
This is for example something that, if we go ahead like @sed-i pushes for and accept to drop the support for `%%juju_topology%%`, also breaks :-)

2022-01-28 16:38 UTC, dstathis approved these changes

2022-02-09 13:37 UTC, simskij commented on metadata.yaml
> +  metrics-endpoint:
> I am thinking that, due to the nature of our charms being themselves monitoring tools, we need to put extra care in the naming, and probably break convention. We must have a discussion in the team about how to name these. cc @simskij

Got it! Added it to the team meeting agenda for next week.

2022-02-09 13:37 UTC, simskij commented on src/prometheus_alert_rules/unit_unavailable.rule
> +expr: up{%%juju_topology%%} < 1
We are not dropping that support, so this is not an issue anymore.

2022-02-09 14:19 UTC, sed-i commented on metadata.yaml
> +  metrics-endpoint:
```yaml
provides:
  custodiet-ipsos-custodes::
```

2022-02-24 20:25 UTC, dstathis submitted a review, later dismissed

2022-03-24 12:03 UTC, mmanciop requested changes

2022-03-24 12:03 UTC, mmanciop commented on src/prometheus_alert_rules/unit_unavailable.rule
> +expr: up{%%juju_topology%%} < 1
We do not need the `%%juju_topology%%` anymore, thanks to `promql_transform`

2022-03-24 12:03 UTC, mmanciop commented
Also, can I please get a matching PR in https://github.com/canonical/cos-lite-bundle ? :-)

2022-03-28 07:28 UTC, simskij commented
[9 votes for `self-*`](https://discourse.charmhub.io/t/how-should-we-call-relations-for-monitoring-cos-charms/5950), let's go with that and only use it for the ones that also provide that relation organically, ie. `self-metrics-endpoint` for Prometheus, `self-logs` for Loki, `self-logs` for Grafana Agent, and `self-dashboards` for Grafana itself.

2022-03-28 23:12 UTC, rbarry82 commented
And so it was written

2022-04-01 14:21 UTC, simskij commented on src/prometheus_alert_rules/unit_unavailable.rule
> +expr: up{%%juju_topology%%} < 1
See https://github.com/canonical/cos-lite-bundle/issues/24

2022-04-01 19:39 UTC, sed-i commented on src/charm.py
> +        # -- Prometheus self-monitoring
```suggestion
        # -- Self-monitoring
```

2022-04-01 19:39 UTC, sed-i commented on src/prometheus_alert_rules/unit_unavailable.rule
> +  severity: critical
Do we need a `self-monitoring` label here?

2022-04-01 19:39 UTC, sed-i commented on src/prometheus_alert_rules/unit_unavailable.rule
> +expr: up{%%juju_topology%%} < 1
Do we need some sort of a low-pass filter here? e.g.
```suggestion
expr: avg_over_time(up{%%juju_topology%%}[1m]) < 0.5
```
or perhaps something using [`changes`](https://prometheus.io/docs/prometheus/latest/querying/functions/#changes)?

2022-04-01 23:29 UTC, rbarry82 commented on src/prometheus_alert_rules/unit_unavailable.rule
> +  severity: critical
Why would we?

2022-04-01 23:29 UTC, rbarry82 commented on src/prometheus_alert_rules/unit_unavailable.rule
> +expr: up{%%juju_topology%%} < 1
Why would we average this?

2022-04-04 07:19 UTC, simskij commented on src/prometheus_alert_rules/unit_unavailable.rule
> +expr: up{%%juju_topology%%} < 1
if it's down, it's down. but we should probably have a somewhat longer `for` than 0m to avoid false positives.

2022-04-04 07:22 UTC, simskij commented on src/prometheus_alert_rules/unit_unavailable.rule
> +  severity: critical
No. That would just increase the cardinality. And remember: the rule is not only for bundle deployments, so it's not necessarily always self-monitoring.

2022-04-04 07:24 UTC, simskij submitted a review, later dismissed

2022-04-04 14:00 UTC, rbarry82 commented on src/prometheus_alert_rules/unit_unavailable.rule
> +expr: up{%%juju_topology%%} < 1
The question then becomes: "what do we think is an acceptable middle ground?"

If there's more than one Grafana unit (which would be a different rule), do we want to alert if one is down for 5 minutes? 10 minutes?

If there's only one, how long do we wait? Prometheus polling is every 15 seconds (plus the default HTTP timeout before the scrape actually fails). On the one hand, this isn't very long. On the other hand, a "busy" Grafana instance can result in an awful lot of user reports if it's down for multiple minutes, and sending an alert _before_ tickets start rolling in is always the goal.

What do we think is a good mix?

2022-04-04 22:50 UTC, sed-i commented on src/prometheus_alert_rules/unit_unavailable.rule
> +expr: up{%%juju_topology%%} < 1
Maybe this is a case for the severity label and multiple alerts in the group?
- one alert with low severity for `up{%%juju_topology%%} < 1` - this one is also something that MLOps would be happy to consume
- another alert with critical severity for `avg_over_time(up{%%juju_topology%%}[1m]) < 0.5`
Tickets will continue to roll until the issue is resolved, not until it is first seen, on which alert fatigue would have an impact too.

2022-04-04 23:02 UTC, sed-i approved these changes

2022-04-06 21:14 UTC, rbarry82 commented on src/prometheus_alert_rules/unit_unavailable.rule
> +expr: up{%%juju_topology%%} < 1
Done.

2022-04-22 10:04 UTC, balbirthomas commented
Looks like integration tests got hung for 6 hours. This looks like the hang on installing agent Juju flayness.

2022-04-27 04:35 UTC, sed-i commented on src/prometheus_alert_rules/unit_unavailable.rule
> +    severity: critical
Should this be one level lower than `GrafanaUnitIsDown`?

```suggestion
    severity: error
```

2022-04-27 04:35 UTC, sed-i commented on src/prometheus_alert_rules/unit_unavailable.rule
> +  expr: up{} < 1
Just curious why the empty brackets.

2022-04-27 04:35 UTC, sed-i commented on src/prometheus_alert_rules/unit_unavailable.rule
> +groups:
This does not seem like a [valid rule file](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/) - a hierarchy level is missing:
```yaml
- name: example
  rules:
```
Add itest? Not sure what the best way to make grafana unavailable though. Firewall rule?

2022-04-27 04:35 UTC, sed-i commented on src/prometheus_alert_rules/unit_unavailable.rule
> +  for: 0m
I suspect this combo would cause the alert to fire right away if the very first scrape fails.
The easiest (but not most accurate) solution would be 
```suggestion
  expr: avg_over_time(up{}[1m]) < 0.5
  for: 1m
```

2022-04-27 04:35 UTC, sed-i commented on tox.ini
> +    git+https://github.com/charmed-kubernetes/pytest-operator.git@67e6eaebf745b40065167e3b599314cb9e1c674a
Should probably use version numbers, if that actually works for this charm (works for me in other charms)
```ini
    juju==2.9.7
    pytest-operator==0.15.0
```

2022-04-27 04:50 UTC, dstathis approved these changes

2022-04-27 07:34 UTC, rbarry82 commented on src/prometheus_alert_rules/unit_unavailable.rule
> +  for: 0m
That's the goal.

2022-04-27 07:36 UTC, rbarry82 commented on src/prometheus_alert_rules/unit_unavailable.rule
> +  expr: up{} < 1
We're automatically injecting topology into the alerts, aren't we?

2022-04-27 07:39 UTC, rbarry82 commented on src/prometheus_alert_rules/unit_unavailable.rule
> +groups:
Skipping integration tests until other pieces are present, and it can be tested as a sum. This is just the first.

I did miss the name, though...

2022-04-27 07:40 UTC, rbarry82 commented on tox.ini
> +    git+https://github.com/charmed-kubernetes/pytest-operator.git@67e6eaebf745b40065167e3b599314cb9e1c674a
The goal is basically to stay on HEAD unless there's a breaking change which forces a specific commit, like we have right now (until libjuju pushes again)

2022-04-27 13:42 UTC, sed-i commented on src/prometheus_alert_rules/unit_unavailable.rule
> +  for: 0m
Not sure what you mean. (This is a minor comment so no big deal anyway)
My impression was:
1. The alert that fires right away is `GrafanaUnitIsUnavailable`, with `severity: error`.
2. `GrafanaUnitIsDown` fires only after it up is flapping (or completely down) for a minute, with `severity: critical`.

2022-04-27 13:43 UTC, sed-i submitted a review, later dismissed

2022-05-10 10:08 UTC, simskij approved these changes

2022-05-26 11:27 UTC, simskij approved these changes

2022-05-26 12:31 UTC, sed-i reviewed
Why commit promql-transform? I though we said we'd rather depend on internet than commit binaries.

2022-05-26 14:30 UTC, rbarry82 commented on lib/charms/grafana_k8s/v0/grafana_dashboard.py
> +    def update_dashboards(self, relation: Relation = None) -> None:
It would be bad for airgapping, but this will get the same thing as Prometheus anyway, and this will be removed.

2022-06-07 12:13 UTC, simskij commented on lib/charms/grafana_k8s/v0/grafana_dashboard.py
> +    def update_dashboards(self, relation: Relation = None) -> None:
Agreed, but rather than pushing binaries, we should consider priming the charm with promql-transform while packing.

2022-06-15 09:21 UTC, simskij commented on src/prometheus_alert_rules/unit_unavailable.rule
> +  expr: up{} < 1
Brackets are not really needed for promql-transform to work, but they don't hurt either. 😅

2022-06-29 12:56 UTC, Abuelodelanada approved these changes

2022-07-04 11:20 UTC, simskij commented on metadata.yaml
> +  metrics-endpoint:
It is still correct. `self-` we decided to only add to the provider-side of something that also is a requirer of the same interface. For instance, for Prometheus `metrics-endpoint` is the requirer, while `self-metrics-endpoint` is the provider.

2022-07-05 12:17 UTC, simskij commented on lib/charms/grafana_k8s/v0/grafana_dashboard.py
> +    def update_dashboards(self, relation: Relation = None) -> None:
@rbarry82 can we please resolve this prior to merging? If we merge with the binary in there, it will be stuck in the reflog unless purged manually, even if we delete it in a subsequent commit, which is something I'd rather not have us do.

2022-07-13 11:54 UTC, balbirthomas approved these changes

2022-07-19 15:01 UTC, merged