Move away from StoredState for Grafana.*Consumer and charm
canonical/grafana-k8s-operator pull request #65
Opened 2022-02-15 00:54 UTC by rbarry82

We can't rely on a peer relation in the aggregator or a provider
charms, so we're left with StoredState there, but get rid of it
from Grafana and the associated Consumer libraries.

Update the tests to match. Since JSON doesn't have a literal
int type, make sure that the relation keys in the tests also are
not bare ints, and that we convert from Stored*

2022-02-15 05:38 UTC, sed-i commented on lib/charms/grafana_k8s/v0/grafana_dashboard.py
> +                self.set_peer_data({k: v})
This interface seems a bit confusing to me - it is called set, but it is really the equivalent of `dict.update`.
Maybe `self.set_peer_data(k1=v1, k2=v2, ...)`?
This way it would be more symmetric with `get_peer_data`.

2022-02-15 05:38 UTC, sed-i commented on lib/charms/grafana_k8s/v0/grafana_source.py
> +        self.set_peer_data({"sources": sources})
Not sure but shouldn't this kind of data go into unit data bag?
Originally it was `_stored`, which is per unit, and now it is per app. Just making sure this is intentional etc.

2022-02-15 05:38 UTC, sed-i commented on lib/charms/grafana_k8s/v0/grafana_source.py
> +        # If there's stored data, merge it and purge it
Would `logger.info` about "data migration" be handy here?

2022-02-15 05:38 UTC, sed-i commented on metadata.yaml
> +  grafana:
Wouldn't this be confusing in `juju status` output? (the Type: peer column is way on the right)
How about "replicas" or "peers"?

2022-02-15 05:38 UTC, sed-i commented on src/charm.py
> +        self._stored.set_default(k8s_service_patched=False, admin_password="")
iirc we said password goes into rel data as well for now (?)

2022-02-15 05:38 UTC, sed-i commented on src/charm.py
> +        self.set_peer_data({"database": {}})
Shouldn't this action be delegated to charm lib, which in turn would `_set_default_data`?

2022-02-15 05:38 UTC, sed-i commented on tests/unit/test_charm.py
> +        self.harness.add_relation("grafana", "grafana")
I suspect that to truly be a peer relation, the app name here must match metadata, i.e. "grafana-k8s".

2022-02-15 05:38 UTC, sed-i commented on tests/unit/test_dashboard_consumer.py
> +        self.harness.add_relation("grafana", "grafana")
"grafana-k8s"?

2022-02-15 05:50 UTC, rbarry82 commented on lib/charms/grafana_k8s/v0/grafana_dashboard.py
> +        data = self._charm.peers.data[self._charm.app].get(key, "")  # type: ignore
They have the same truth value

2022-02-15 05:51 UTC, rbarry82 commented on lib/charms/grafana_k8s/v0/grafana_source.py
> +        self.set_peer_data({"sources": sources})
We cannot rely on unit peer bags for solitary units

2022-02-15 05:52 UTC, rbarry82 commented on lib/charms/grafana_k8s/v0/grafana_source.py
> +        # If there's stored data, merge it and purge it
We don’t lot about the other conversion either. If anything, debug. This is housekeeping which an admin doesn’t need to worry about

2022-02-15 05:53 UTC, rbarry82 commented on metadata.yaml
> +  grafana:
This matches the practice in other charms

2022-02-15 05:53 UTC, rbarry82 commented on src/charm.py
> +        self._stored.set_default(k8s_service_patched=False, admin_password="")
Let’s not muddy this patch with other issues

2022-02-15 05:53 UTC, rbarry82 commented on src/charm.py
> +        self.set_peer_data({"database": {}})
Database doesn’t belong to libs.

2022-02-15 05:54 UTC, rbarry82 commented on tests/unit/test_charm.py
> +        self.harness.add_relation("grafana", "grafana")
It does not.

2022-02-15 05:58 UTC, rbarry82 commented on lib/charms/grafana_k8s/v0/grafana_dashboard.py
> +                self.set_peer_data({k: v})
This is more to do with the annoying way Python handles nested dict keys `peer.data[app][type][key]`, and it common in libraries doing the same thing (mostly k/v stores or event streaming)

The “right” way is pickling, but it makes `show-unit` really bad

2022-02-15 06:03 UTC, sed-i commented on tests/unit/test_charm.py
> +        self.harness.add_relation("grafana", "grafana")
What do you mean - as long as the relation name is a peer relation, harness doesn't care about the app name?
BTW metadata is `name: grafana-k8s`.

2022-02-16 00:10 UTC, rbarry82 commented on tests/unit/test_charm.py
> +        self.harness.add_relation("grafana", "grafana")
It does not. The signature in the harness is:

```python
add_relation(self, relation_name: str, remote_app: str)
```

As long as the relation name matches ([which is `grafana`](https://github.com/canonical/grafana-k8s-operator/pull/65/files#diff-d186204ea7abb85bbadd9d94ab29d5bcefcc43d6a0ed06015e98a71b2f099423R37)), this is fine. The _names_ of the applications in peer data don't actually matter to the harness, even though in practice the odds of having another unit in peer relation with a name which doesn't match is zero

2022-02-16 01:31 UTC, rbarry82 commented on lib/charms/grafana_k8s/v0/grafana_dashboard.py
> +            self._charm.peers.data[self._charm.app][k] = json.dumps(v)  # type: ignore
I tested this quite a bit today, and yes, it's reliable

2022-02-16 01:32 UTC, rbarry82 commented on lib/charms/grafana_k8s/v0/grafana_dashboard.py
> +                self.set_peer_data({k: v})
This is updated to be `set_peer_data(key, data: Any)`

Like `StoredState`, the data is mostly set "as a blob", so individual updates don't make much sense.

2022-02-24 21:01 UTC, Abuelodelanada approved these changes

2022-02-24 21:01 UTC, Abuelodelanada commented on src/charm.py
> +        """Put information into the peer data bucket instead of `StoredState`."""
Docstring shouldn't be something like:

"""Retrieve information from the peer data bucket instead of `StoredState`."""

2022-02-24 21:17 UTC, sed-i commented on src/charm.py
> +        rel = self.model.get_relation(self.app)
Should this be `self.app.name`?
And why not `PEER`?

2022-02-24 21:17 UTC, sed-i commented on tests/integration/test_multiple_units.py
> +    )
```suggestion
    ops_test.model.wait_for_idle(apps=[grafana_app_name, tester_app_name], status="active")
```

2022-02-24 21:17 UTC, sed-i commented on tests/integration/test_multiple_units.py
> +    assert ops_test.model.applications[tester_app_name].units[0].workload_status == "active"
These 3 lines seem to be equivalent to `wait_for_idle`?

2022-02-24 21:17 UTC, sed-i commented on tests/unit/test_charm.py
> +        self.harness.add_relation("grafana", "grafana")
ok. I would still choose the less confusing app name though.

2022-02-25 12:27 UTC, rbarry82 commented on src/charm.py
> +        self._stored.set_default(k8s_service_patched=False, admin_password="")
Right, but not "share the password across units in relation data" :)

Some of the Stored* makes sense to keep anyway, so I should rename the PR to reflect the fact that it's _just_ app/unit data being moved.

2022-02-25 12:28 UTC, rbarry82 commented on tests/unit/test_charm.py
> +        self.harness.add_relation("grafana", "grafana")
For unit testing, it probably doesn't matter, but I picked this because it's also what `mongo` uses and several other charms. It appears to be more or less a de-facto standard.

2022-02-25 12:34 UTC, rbarry82 commented on lib/charms/grafana_k8s/v0/grafana_dashboard.py
> +        # StoredState here
There's not enough information about this. We know that _some_ reactive charms communicate in an RPC-like manner as a conversation to negotiate information. None of the Grafana ones I've found (yet), but better to be safe than sorry, and this is in the Aggregator in any case.

2022-02-25 12:36 UTC, rbarry82 commented on lib/charms/grafana_k8s/v0/grafana_source.py
> +        # break compatibility
Even if there's nothing in `StoredState`, it still needs to be initialized since we can't guarantee which versions will be used.

2022-02-25 12:59 UTC, rbarry82 commented on lib/charms/grafana_k8s/v0/grafana_source.py
> +        if self._charm.unit.is_leader():
No, there is not. Leaders set the data and won't get this event anyway. This line is possibly superfluous, but harmless.

Integration tests cover this because Harness does not behave nicely with multiple units

2022-02-25 15:17 UTC, sed-i approved these changes

2022-02-25 15:20 UTC, rbarry82 commented on tests/integration/test_multiple_units.py
> +    assert ops_test.model.applications[tester_app_name].units[0].workload_status == "active"
It actually waits for idle just above this, the assertion because we want to really _know_ they're idle instead of hitting the `check_freq` in libjuju for a unit which has been created but not actually doing anything yet.

This is more of a problem when scaling down integration tests, but it doesn't hurt here.

2022-02-25 18:38 UTC, sed-i approved these changes

2022-02-26 00:35 UTC, dstathis requested changes

2022-02-26 00:35 UTC, dstathis commented on lib/charms/grafana_k8s/v0/grafana_dashboard.py
> +            self._charm.on[DEFAULT_PEER_NAME].relation_changed,
There appears to be no way to set the pear relation name to anything other than default. This seems like an issue.

2022-02-26 00:35 UTC, dstathis commented on lib/charms/grafana_k8s/v0/grafana_source.py
> +            self._charm.on[DEFAULT_PEER_NAME].relation_changed,
Same thing here about not being able to set peer relation name.

2022-02-26 00:35 UTC, dstathis commented on lib/charms/grafana_k8s/v0/grafana_source.py
> +                stored_sources[rel_id] = [
Is this supposed to be a global?

2022-02-26 00:35 UTC, dstathis commented on src/charm.py
>          return len(rel.units) > 0 if rel is not None else False
I know there wasn't an actual change here but I suspect you may want planned units here

2022-02-26 00:40 UTC, rbarry82 commented on lib/charms/grafana_k8s/v0/grafana_dashboard.py
> +            self._charm.on[DEFAULT_PEER_NAME].relation_changed,
Considering it's only implemented on the consumer side, since we can't rely on peer data buckets necessarily existing on providers at all...

2022-02-26 00:53 UTC, rbarry82 commented on lib/charms/grafana_k8s/v0/grafana_source.py
> +                stored_sources[rel_id] = [
It's an instance variable set just above this

2022-02-26 00:59 UTC, rbarry82 commented on src/charm.py
>          return len(rel.units) > 0 if rel is not None else False
It's actually completely unused since we don't (and will not) set up an external traditional DB

2022-02-26 01:14 UTC, dstathis approved these changes

2022-02-26 01:19 UTC, merged