Make sure Grafana is up before hitting the API to check password validity
canonical/grafana-k8s-operator pull request #76
Opened 2022-03-15 15:15 UTC by rbarry82

Since an HTTPError is also checked for in the password action, it's
possible to encounter a race where the action informs users that the
password has been changed when Grafana is simply not available yet.

No tests since Harness cannot check actions and we can't reliably reproduce a race in the integration tests.

2022-03-15 15:20 UTC, sed-i requested changes

2022-03-15 15:20 UTC, sed-i commented on src/charm.py
> +                }
```suggestion
                {
                    "admin-password": "",  # or omit key entirely
                    "error": "Grafana is not reachable yet. Please try again in a few minutes"
                }
```

2022-03-15 15:20 UTC, sed-i commented on src/charm.py
> +                }
Or even better: `event.fail()`

2022-03-15 16:19 UTC, sed-i submitted a review, later dismissed

2022-03-15 19:05 UTC, mmanciop submitted a review, later dismissed
Change looks OK, but it deserves a unit test. It should be easy to do with a self.harness.begin() and directly invoking the action method from self.harness.charm passing a mock of ActionEvent

2022-03-15 19:45 UTC, mmanciop commented
> I should have clarified :| Of course, it's a Turing-complete language, anything _can_ be done. Whether or not we _should_ attempt to fake out actions by manually invoking private methods and mocking `ActionEvent` is another question.

Tbh this solution does not horrify me much. AFAICT OF does comparably little lifting for actions, as opposed to relations.

> I'll write the test here, but we should really make an effort to push on OF to implement actions in harness before this becomes a pattern.

Yep we should.

2022-03-16 08:46 UTC, mmanciop approved these changes
:heart:

2022-03-17 02:24 UTC, sed-i approved these changes

2022-03-17 11:51 UTC, mmanciop approved these changes

2022-03-17 11:52 UTC, merged