Adds config to enable auth proxy
canonical/grafana-k8s-operator pull request #80
Opened 2022-03-16 21:25 UTC by gruyaume

- Add config for Grafana to let a HTTP reverse proxy handle authentication.
- Improves how Grafana's configuration file is generated based on Juju configs and relationship data

2022-03-17 03:02 UTC, mmanciop requested changes
I feel handling authentication through a reverse proxy belongs to the interplay with an Ingress charm. We are looking this sprint into integrating grafana-k8s with traefik-k8s, although we have not yet looked into the Auth aspect of it. I think we should not add this configuration option, but rather discuss the use case in the scope of ingress.

2022-03-17 12:19 UTC, gruyaume commented
> I feel handling authentication through a reverse proxy belongs to the interplay with an Ingress charm. We are looking this sprint into integrating grafana-k8s with traefik-k8s, although we have not yet looked into the Auth aspect of it. I think we should not add this configuration option, but rather discuss the use case in the scope of ingress.

I agree that making auth proxy configurable through a relationship makes sense. However, I don't think that it has to belong in the ingress. For example in our case we don't use ingress and need this auth proxy configured.

2022-03-18 13:52 UTC, mmanciop commented
> > I feel handling authentication through a reverse proxy belongs to the interplay with an Ingress charm. We are looking this sprint into integrating grafana-k8s with traefik-k8s, although we have not yet looked into the Auth aspect of it. I think we should not add this configuration option, but rather discuss the use case in the scope of ingress.
> 
> I agree that making auth proxy configurable through a relationship makes sense. However, I don't think that it has to belong in the ingress. For example in our case we don't use ingress and need this auth proxy configured.

I understand that you have this need, but exposing the configuration like this, for every Juju admin to wonder about, is not right either. You actually seem to use an ingress-like charm, namely https://github.com/canonical/charmed-magma/tree/main/orchestrator-bundle/nms-magmalte-operator . Since that is running a reverse proxy in front of Grafana (and other stuff as well), it could very well implement the provider side of the `ingress` relation.

2022-03-18 14:27 UTC, gruyaume commented
> > > I feel handling authentication through a reverse proxy belongs to the interplay with an Ingress charm. We are looking this sprint into integrating grafana-k8s with traefik-k8s, although we have not yet looked into the Auth aspect of it. I think we should not add this configuration option, but rather discuss the use case in the scope of ingress.
> > 
> > 
> > I agree that making auth proxy configurable through a relationship makes sense. However, I don't think that it has to belong in the ingress. For example in our case we don't use ingress and need this auth proxy configured.
> 
> I understand that you have this need, but exposing the configuration like this, for every Juju admin to wonder about, is not right either. You actually seem to use an ingress-like charm, namely https://github.com/canonical/charmed-magma/tree/main/orchestrator-bundle/nms-magmalte-operator . Since that is running a reverse proxy in front of Grafana (and other stuff as well), it could very well implement the provider side of the `ingress` relation.
> 
> Now, for completeness: if you did retrofit https://github.com/canonical/charmed-magma/tree/main/orchestrator-bundle/nms-magmalte-operator to implement the `ingress` relation, you still would not get the enablement of the auth proxy out of it. But that is a much better discussion to be had in the scope of "How do ingress-like charms relate with authentication of their downstreams?"

Yes I fully agree about not having this exposed through a config. Let me know how I can help with this ingress relationship you are referring.

For reference, here's the complete grafana.ini config that is used in our context:

```
[users]
allow_sign_up = false
auto_assign_org = false

[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = false

[server]
root_url = /grafana
```

2022-03-18 14:35 UTC, closed without merging