[DRAFT] Add sqlite streaming from primaries to secondaries
canonical/grafana-k8s-operator pull request #83
Opened 2022-03-22 10:08 UTC by rbarry82

## Issue
Considering that is it not possible to `limit` the number of units
which may be started in a Juju application, it's possible for
more than one Grafana unit to be initialized. MOST of the data
which is present is propagated though libraries and across relation
interfaces as dashboards/datasources, but user interaction and
logins with the Grafana UI itself may result in changes.

Without a shared database, scaling the application up or down could
result in units with different administrative passwords, dashboards
imported from the marketplace, manually added users/groups, or more.

## Solution
When a charm is elected as the leader, it will now start `litestream`
to serve changes over GRPC/HTTP. 

## Context
This additionally requires changing
the a sqlite pragma to Grafana. However, this is a long-requested
feature for Grafana itself, with hundreds of users reporting that
it actually reduced the frequency of database locking [see the
issue](https://github.com/grafana/grafana/issues/16638), so this is
reasonably safe.

## Testing Instructions

## Release Notes

Use litestream for primary/secondary sqlite streaming.

2022-03-22 19:27 UTC, jameinel commented
note that you could have all units other than the leader come up in a
Blocked state.

On Tue, Mar 22, 2022, 05:08 Ryan Barry ***@***.***> wrote:

> Issue
>
> Considering that is it not possible to limit the number of units
> which may be started in a Juju application, it's possible for
> more than one Grafana unit to be initialized. MOST of the data
> which is present is propagated though libraries and across relation
> interfaces as dashboards/datasources, but user interaction and
> logins with the Grafana UI itself may result in changes.
>
> Without a shared database, scaling the application up or down could
> result in units with different administrative passwords, dashboards
> imported from the marketplace, manually added users/groups, or more.
> Solution
>
> When a charm is elected as the leader, it will now start litestream
> to serve changes over GRPC/HTTP.
> Context
>
> This additionally requires changing
> the a sqlite pragma to Grafana. However, this is a long-requested
> feature for Grafana itself, with hundreds of users reporting that
> it actually reduced the frequency of database locking see the
> issue <https://github.com/grafana/grafana/issues/16638>, so this is
> reasonably safe.
> Testing Instructions Release Notes
>
> Use litestream for primary/secondary sqlite streaming.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/canonical/grafana-k8s-operator/pull/83
> Commit Summary
>
>    - 225def8
>    <https://github.com/canonical/grafana-k8s-operator/pull/83/commits/225def860cb24fc0a99c036fd93f818115c4451c>
>    Add sqlite streaming from primaries to secondaries
>
> File Changes
>
> (3 files <https://github.com/canonical/grafana-k8s-operator/pull/83/files>
> )
>
>    - *M* metadata.yaml
>    <https://github.com/canonical/grafana-k8s-operator/pull/83/files#diff-d186204ea7abb85bbadd9d94ab29d5bcefcc43d6a0ed06015e98a71b2f099423>
>    (9)
>    - *M* src/charm.py
>    <https://github.com/canonical/grafana-k8s-operator/pull/83/files#diff-b9ed39bbc9c0387bd3e07da31d13373745534a1cd723d3e292c73496b12e307c>
>    (129)
>    - *M* tests/unit/test_charm.py
>    <https://github.com/canonical/grafana-k8s-operator/pull/83/files#diff-0580ab9aef31b44580478eb270ec3422c5e6fef35df585fecb3a68317e246809>
>    (17)
>
> Patch Links:
>
>    - https://github.com/canonical/grafana-k8s-operator/pull/83.patch
>    - https://github.com/canonical/grafana-k8s-operator/pull/83.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/canonical/grafana-k8s-operator/pull/83>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABRQ7JMD6KVLSMFNE4MZTLVBGL2TANCNFSM5RKLUKBQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-03-22 19:37 UTC, mmanciop commented
> note that you could have all units other than the leader come up in a Blocked state.
> […](#)

We discussed all options at length and they are pretty consistently terrible.

2022-08-10 07:32 UTC, jnsgruk commented on charmcraft.yaml
> +      curl -L https://github.com/CompuRoot/static-sqlite3/releases/latest/download/sqlite3 -o sqlite-static
Note that is is architecture specific, could we use one of the [advanced grammars](https://snapcraft.io/docs/snapcraft-advanced-grammar) here? This is a rough guess/pseudo-code, but something like:

```yaml
static-sqlite3:
  plugin: dump
  source:
    on amd64: https://github.com/CompuRoot/static-sqlite3/releases/latest/download/sqlite3
    on arm64: https://github.com/CompuRoot/static-sqlite3/releases/latest/download/sqlite3-arm64
  override-stage: |
    chmod +x sqlite*
    cp sqlite* $CRAFT_PART_INSTALL/
```

2022-08-10 11:27 UTC, rbarry82 commented on charmcraft.yaml
> +      curl -L https://github.com/CompuRoot/static-sqlite3/releases/latest/download/sqlite3 -o sqlite-static
It is, yeah. Realistically, the static build here is just a community effort which has enough stars. It's pretty trivial to do, and we may want to just set up our own tiny repo which does it ourselves (or I could do it on my own GH account).

We [already use the advanced grammars in other charms](https://github.com/canonical/prometheus-k8s-operator/blob/main/charmcraft.yaml#L20) so we know they work 👍 It took a little experimenting, but great afterwards.

2022-08-10 12:57 UTC, simskij commented on charmcraft.yaml
> +      curl -L https://github.com/CompuRoot/static-sqlite3/releases/latest/download/sqlite3 -o sqlite-static
Moved to https://github.com/canonical/grafana-k8s-operator/issues/112 :)

2022-08-10 13:41 UTC, sed-i commented on src/charm.py
> +        }
We should probably use the exact same names as in metadata.

OTOH, now we have `"workload"` literals everywhere in the code. Would it make sense to use a more "static" approach?
```python
self.container_grafana = ...
self.container_litestram = ...
self.containers = (self.container_grafana, self.container_litestream)
```

2022-08-10 13:41 UTC, sed-i commented on src/charm.py
> +        self.framework.observe(self.on[PEER].relation_changed, self._on_peer_data_changed)
I forget, is / could / should there be interaction between the named peer and the container name?

I.e. is it possible / useful to have
```yaml
peers:
  grafana:
    interface: grafana_peers
  litestream:
    interface: litestream_peers
```

2022-08-10 13:41 UTC, sed-i commented on src/charm.py
> +            self._configure_replication(True)
Should we observe `leader_settings_changed`? If not, should this be:
```suggestion
        self._configure_replication(self.unit.is_leader())
```

Not sure I fully understand the interaction with `_on_peer_data_changed`. Add comment?

2022-08-10 13:41 UTC, sed-i commented on charmcraft.yaml
> +  static-sqlite3:
Could/should this be another container?

2022-08-10 13:41 UTC, sed-i commented on src/charm.py
> +            container.push("/etc/litestream.yml", yaml.dump(litestream_config), make_dirs=True)
This can still result in tracebacks in the log.
I think we saw `can_connect` needs to be used in tandem with try-except after the ops context mgr was removed.

2022-08-10 13:41 UTC, sed-i commented on src/charm.py
> +            pragma.wait()
Is this safe to do while the other binaries are running?

2022-08-10 13:41 UTC, sed-i commented on src/charm.py
>              )
If the exec fails, it looks like it will "never" be retried?

2022-08-10 13:41 UTC, sed-i commented on src/charm.py
> +                self.containers["replication"].start("litestream")
I forget, would those lines be covered by `.replan()`?

2022-08-10 13:41 UTC, sed-i commented on src/charm.py
> +    def _build_replication(self, primary: bool) -> Layer:
Would this increase clarity?

```suggestion
    def _build_litestream_layer(self, primary: bool) -> Layer:
```

2022-08-10 13:41 UTC, sed-i commented on src/charm.py
> +    def restart_litestream(self, leader: bool) -> None:
Should we add utests around the contents of the pebble layer under various circumstances?

2022-08-11 10:24 UTC, simskij commented on src/charm.py
> +        }
I'm in favor of being more specific. `grafana` and `replication` seems reasonable to me. We might want to switch out litestream at some point, but we are very unlikely to switch out grafana in the grafana charm :P

2022-08-11 10:28 UTC, simskij commented on src/charm.py
> +    def _configure_replication(self, leader: bool) -> None:
Having a single boolean argument to handle flow control is an anti-pattern. Please split this into two functions and call them accordingly.

2022-08-11 10:29 UTC, simskij commented on charmcraft.yaml
> +  static-sqlite3:
Nope, it can't. SQLite targets a file rather than a remote server over a connection, so they need to be in the same container. :)

2022-08-11 10:30 UTC, simskij commented on src/charm.py
> +            container.push("/etc/litestream.yml", yaml.dump(litestream_config), make_dirs=True)
Are you saying can_connect is now raising exceptions? Seems like something we should ask our friends in the OF team to change in that case.

2022-08-11 10:31 UTC, simskij commented on src/charm.py
> +                self.containers["replication"].start("litestream")
Only if there has been a change to the service.

2022-08-11 10:32 UTC, simskij commented on src/charm.py
> +    def _build_replication(self, primary: bool) -> Layer:
Nah, it's overly specific given that we might want to switch out our replication component at some point. I'd suggest keeping it as is.

2022-08-11 10:32 UTC, simskij commented on src/charm.py
> +    def restart_litestream(self, leader: bool) -> None:
Yes, that sounds like a good idea.

2022-08-11 10:36 UTC, simskij commented on src/charm.py
> +            self.containers["replication"].get_plan().services
Why does this need to be in a separate container? Wouldn't it make sense to run both of them in the workload container?

2022-08-11 10:45 UTC, sed-i commented on charmcraft.yaml
> +  static-sqlite3:
Could have `shared: true` in metadata.yaml has under `storage` but that is besides the point :)

2022-08-11 10:45 UTC, sed-i commented on src/charm.py
> +            container.push("/etc/litestream.yml", yaml.dump(litestream_config), make_dirs=True)
`can_connect` is a "point in time" so no guarantees about 1ms in the future.

2022-08-11 17:24 UTC, sed-i commented on tests/integration/helpers.py
> +    return action["admin-password"]
`.results` is [still in there](https://github.com/juju/python-libjuju/blob/master/juju/action.py).
Rerun the tests?

2022-08-12 10:40 UTC, rbarry82 commented on src/charm.py
> +        }
That was kind of the idea. Maybe even as part of this PR once ingress is there. 

Initially (at the initial date of the PR), HTTP replication in `litestream` wasn't present yet. In the meantime, it was added as an experimental feature. And now it's been removed from the roadmap (still will work, but as it's "experimental" with a superceding solution, it may not get fixes).

Instead, there is LiteFS, which _had_ (has) a soft dependency on Consul, but got support for a "static" leaseholder (which we could use Juju leadership for) [literally four days ago](https://github.com/superfly/litefs/commit/db1ff107e7dbbc6a26f718087ac798e41333495e). Similarly, if Grafana manages to untie whatever they're doing with their forked version of xorm, changing this to cockroach/tidb or some multi-primary "real" distributed replicated kube-native database is possible.

In any/all of those cases, it would no longer be litestream.

If we want to get rid of the literal, if anything, I'd just change the dict key to a constant, but it's really overkill just to avoid a literal lookup for a dict key, which is completely Pythonic anyway.

2022-08-12 10:41 UTC, rbarry82 commented on src/charm.py
> +        self.framework.observe(self.on[PEER].relation_changed, self._on_peer_data_changed)
Not really, no. The only information the replication peers need is set as part of the layer/service instantiation. They don't share any application/configuration level data we'd have in `litestream_peers`, for example.

2022-08-12 10:48 UTC, rbarry82 commented on src/charm.py
> +            self.containers["replication"].get_plan().services
Only if we want yet another repo which builds the litestream binary, or to push another dep into the charm which must be pushed into the container from [here](https://github.com/benbjohnson/litestream/releases/tag/v0.4.0-beta.2) -- last release in April, and it has a long/ugly git hash. As with the other comment, since LiteFS is a project now, it's unclear whether this will ever be realized.

Similarly, as with litefs, keeping this separated out and using the Docker image from the upstream maintainer until it "settles out", and Rockcraft settles out, and we get a more complete story around it... If we do use LiteFS with the new "static" master leasing, fuse and `libfuse-dev` are _runtime_ dependencies. We can't be grabbing those on install in any kind of airgapped environments it's ever deployed it. Having it as a separate container lets containers be what they are good at

2022-08-12 11:01 UTC, rbarry82 commented on src/charm.py
> +    def _configure_replication(self, leader: bool) -> None:
It really is not an anti-pattern or a code smell in Python. PEP532 is almost a formalization of this. 

The alternative is to move the leadership checking from above into this block, but a second function which does the same thing (minus one update to the dict) is overnormalizing the code, and will make both grokking (for new contributors) and updating the code less obvious, as now any changes would need to be made in two places.

The leadership check can be done here, or as part of an argument, but this method must both be able to be easily invoked on any event where leadership changes (regardless of whether this unit is the leader or not) and to be able to determine whether or not it _is_ the leader, ideally as a "single entrypoint".

Splitting this into two functions, other than risk of "missing" part of it on any change/bug, would require, basically:

```python
def _on_config_changed|_on_leader_elected(....):
   ...
   if self.unit.is_leader():
     configure_primary_replicaa()
   else:
     configure_secondary_replica()
```

Where those methods do more or less the same thing, minus one dict key. If a solution ever comes into play for multi-primary replication, they'd need to be combined, or determine the backend replication type and do exactly the same thing.

Whether the leadership check is done as part of this method or as an argument, keeping this structure lowers the maintenance effort in the future.

2022-08-12 11:04 UTC, rbarry82 commented on src/charm.py
> +            container.push("/etc/litestream.yml", yaml.dump(litestream_config), make_dirs=True)
While true, and I lost that battle with the initial contextmanager (which was then removed from OF), the chances of Pebble going away when the next instruction is executed are low, particularly considering that `config_changed` is an uncommon event during charm shutdown/removal. We do perform that kind of exception checking other places in the charm, where `relation-broken` events may result in a "storm" of changes during shutdown, but until we see tracebacks in the logs on this one, we may be able to escape the handler here.

2022-08-12 11:05 UTC, rbarry82 commented on src/charm.py
> +            pragma.wait()
Yes. `sqlite` can be accessed concurrently, and it's not a daemon, so there's no restart needed. On updates, it often performs table locks (rather than row locks like other databases) to prevent concurrent access from causing "problems", but you can just start another `sqlite` process and happily query/connect while other things have it open.

2022-08-12 11:09 UTC, rbarry82 commented on tests/integration/helpers.py
> +    return action["admin-password"]
Added [after I changed this and before you checked](https://github.com/juju/python-libjuju/commit/fb837cc2a630bb407cf059dc1871a2cc832cf801). If `.results` is part of the "old" client, the fact that we stumbled upon this breakage may as well be a `DeprecationWarning`. I'd rather keep `action["results"]` than go back to `action.results[...]` if `.results` is part of the "old" client and will be potentially be removed someday.

2022-08-12 11:13 UTC, rbarry82 commented on src/charm.py
>              )
This code is not new. An exec failure will not result in a `ConnectionError`, it's an [`ExecError`](https://github.com/canonical/operator/blob/c2ffe250a5cac347709caa60c4863c593d85afe8/ops/pebble.py#L1241), so that would not be caught and the charm would block on a failed action.

The existing `except ConnectionError...` is one of the other "`can_connect()` is a point-in-time-check, so make sure we don't spray the juju log with backtraces if something happens to Pebble we're performing operations" checks.

2022-08-12 11:17 UTC, rbarry82 commented on src/charm.py
> +    def restart_litestream(self, leader: bool) -> None:
Honestly, no. We should not. Unit tests are not a sufficient check. The container is not "really" running, and unit tests can't verify whether or not `sqlite` actually went to `journal_mode=wal`, and we don't do anything to the litestream container other than pushing a YAML.

We _can_ check the contents of that (and a unit test to ensure that the `pebble.Layer` has the "correct" leader environment variable from `_build_replication`). I do intend to write those tests. Broadly, though, most of the verification must be done through integration tests where it is actually executing.

2022-08-12 11:32 UTC, rbarry82 commented on charmcraft.yaml
> +  static-sqlite3:
Wouldn't actually solve this problem, which is "should we install `sqlite` in the Grafana ROCK or the charm container?" We don't want to do it at runtime due to airgapped installs, so it should be "baked in", and "baking" it into the charm, while a small addition, is potentially something we don't want to stick on as image bloat.

`shared: true` is something we should not use. It's not related to the need to have a sqlite binary somehow, but "all units should share the storage" is... problematic. There are always concerns about multiple _different_ systems accessing the same file without some kind of arbitrator (in the past, this would have been lustre, gfs2, etc; now it would be ceph, gluster, etc; or it could be the NFS server in either case, or `sanlock`, or...) because otherwise "raw" access can easily lead to one system stomping on another one and it all gets corrupted.

In this case, though, `shared: true` also means "map the same PVC to all the units". Imagine that we have 3 compute nodes in a test for some reason, and hostpath storage. A unit starts up on another node. What happens? 

The volume mounts in a pod are shared (`/var/lib/grafana`, for example), and that's what we want here -- shared inside the _pod_, not shared across the charm, which is more the domain of "I have a LUN that I'm presenting"

2022-08-12 18:29 UTC, rbarry82 commented on src/charm.py
>              )
We do not go into error state intentionally. To be clear, there are five different places in the code where we have `except ConnectionError`. They have all been there for over a year. They were all present to squelch errors in the logs around Pebble shutdown.

There are five places because Grafana does not use a "common exit hook" or "common `_configure` method". The handling of added datasources/dashboards into `/etc/grafana/provisioning/{type}` does not require a complete reconfiguration or restart. Just writing out files.

These occurred because, for example, `juju remove-application grafana prometheus spring-music` may fire `relation-[departed|broken]` events for datasources/dashboards, and the charm code is trying to push files without knowing that Juju/k8s is killing the pod, and Pebble disappeared after `can_connect()`. 

We really, absolutely do not need to write tests for "if the Pebble socket cannot be reached after `can_connect()` _and_ the charm is still executing, there should be an ERROR level log". It is not an intentional case in any way. Instead, it's a tradeoff to say "hey -- Grafana encountered a race, so we logged this instead of 50 lines of Python stack traces from `ops.pebble`". 

If "Pebble socket does not exist or is not responsive" is not explicit enough for the cause of this in the code, I'm not sure what would be.

2022-08-24 10:01 UTC, simskij requested changes
This currently breaks immediately on deploy:

```
$ juju deploy \
    ./grafana-k8s_ubuntu-20.04-amd64.charm grafana \
    --resource grafana-image=docker.io/ubuntu/grafana:8.2-22.04_beta \
    --resource litestream-image=docker.io/litestream/litestream:0.4.0-beta.2
```

```
$ juju status
Model        Controller  Cloud/Region        Version  SLA          Timestamp
sqlite-test  uk8s        microk8s/localhost  2.9.31   unsupported  11:58:47+02:00

App      Version  Status   Scale  Charm        Channel  Rev  Address         Exposed  Message
grafana           waiting      1  grafana-k8s             0  10.152.183.208  no       installing agent

Unit        Workload  Agent  Address     Ports  Message
grafana/0*  error     idle   10.1.14.18         hook failed: "config-changed"
```

with the following log output:
```
nit-grafana-0: 11:58:43 ERROR unit.grafana/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/pebble.py", line 1553, in _request_raw
    response = self.opener.open(request, timeout=self.timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/charm.py", line 787, in <module>
    main(GrafanaCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/main.py", line 438, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/main.py", line 150, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 839, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 914, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 149, in _on_config_changed
    self._configure()
  File "./src/charm.py", line 234, in _configure
    self.restart_grafana()
  File "./src/charm.py", line 533, in restart_grafana
    pragma = self.containers["workload"].exec(
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/model.py", line 1904, in exec
    return self._pebble.exec(
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/pebble.py", line 2281, in exec
    resp = self._request('POST', '/v1/exec', body=body)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/pebble.py", line 1515, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/pebble.py", line 1564, in _request_raw
    raise APIError(body, code, status, message)
ops.pebble.APIError: exec: "sqlite3": executable file not found in $PATH
unit-grafana-0: 11:58:43 ERROR juju.worker.uniter.operation hook "config-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-grafana-0: 11:58:43 INFO juju.worker.uniter awaiting error resolution for "config-changed" hook
```

Waiting for the charm to settle and hopefully self-heal makes no difference

2022-08-27 23:20 UTC, rbarry82 commented
Let's see. I have spent about two days trying to reproduce that error, unsuccessfully. It's clear from the logs that Pebble is crashing, but there's not an identifiable cause for this from the charm. 

I added a separate poller since `can_connect` is a point-in-time check, and it will fail out after 2 seconds, though a `pebble.APIError` is pretty much impossible to work around from the charm side.

Integration test failures right now appear unrelated (permission errors with `sg`, and the run before this ended up with Juju 2.9.29 somehow even though we aren't pinned anymore). Passes locally. Please recheck when you get a chance @simskij

2022-08-29 08:10 UTC, simskij commented
Now it's no longer erroring out. It is still not syncing, however.

### Attempt 1
- Build and deploy grafana-k8s from 33043b84ad51b917ad1b8e4b64ba8544d2876a61 with the images in 	`upstream-source` with scale 1.
- Scale application to 2.
- Log in with the same password in both - works.
- Invite a user from leader - not synced over
- Invite a user from follower - not synced over which is expected
- Install a plugin from leader - not synced over

Then I got logged out of follower, and the password no longer worked to log in.

### Attempt 2:
- Clean up and redeploy one unit
- Create a dashboard
- Scale up to two units - no sync
- Create another dashboard - no sync

Then I got logged out again, and the password no longer worked.

```sh
Model        Controller  Cloud/Region        Version  SLA          Timestamp
sqlite-test  uk8s        microk8s/localhost  2.9.31   unsupported  09:46:01+02:00

App      Version  Status  Scale  Charm        Channel  Rev  Address         Exposed  Message
grafana           active      2  grafana-k8s             3  10.152.183.125  no       

Unit        Workload  Agent  Address     Ports  Message
grafana/0*  active    idle   10.1.14.11         
grafana/1   active    idle   10.1.14.22
```

```
controller-0: 09:22:15 INFO juju.worker.caasapplicationprovisioner.runner start "grafana"
unit-grafana-0: 09:22:27 INFO juju.cmd running containerAgent [2.9.31 93e5d53b99a0fc4e5294972a6c3bd3950defc0d1 gc go1.18.2]
unit-grafana-0: 09:22:27 INFO juju.cmd.containeragent.unit start "unit"
unit-grafana-0: 09:22:27 INFO juju.worker.upgradesteps upgrade steps for 2.9.31 have already been run.
unit-grafana-0: 09:22:27 INFO juju.worker.probehttpserver starting http server on [::]:3856
unit-grafana-0: 09:22:27 INFO juju.api cannot resolve "controller-service.controller-uk8s.svc.cluster.local": lookup controller-service.controller-uk8s.svc.cluster.local: operation was canceled
unit-grafana-0: 09:22:27 INFO juju.api connection established to "wss://10.152.183.235:17070/model/adfc6a16-fbca-44be-8585-f64d38457af5/api"
unit-grafana-0: 09:22:27 INFO juju.worker.apicaller [adfc6a] "unit-grafana-0" successfully connected to "10.152.183.235:17070"
unit-grafana-0: 09:22:27 INFO juju.worker.migrationminion migration phase is now: NONE
unit-grafana-0: 09:22:27 INFO juju.worker.logger logger worker started
unit-grafana-0: 09:22:27 WARNING juju.worker.proxyupdater unable to set snap core settings [proxy.http= proxy.https= proxy.store=]: exec: "snap": executable file not found in $PATH, output: ""
unit-grafana-0: 09:22:27 INFO juju.worker.caasupgrader abort check blocked until version event received
unit-grafana-0: 09:22:27 INFO juju.worker.caasupgrader unblocking abort check
unit-grafana-0: 09:22:27 INFO juju.worker.leadership grafana/0 promoted to leadership of grafana
unit-grafana-0: 09:22:27 INFO juju.agent.tools ensure jujuc symlinks in /var/lib/juju/tools/unit-grafana-0
unit-grafana-0: 09:22:27 INFO juju.worker.uniter unit "grafana/0" started
unit-grafana-0: 09:22:27 INFO juju.worker.uniter resuming charm install
unit-grafana-0: 09:22:27 INFO juju.worker.uniter.charm downloading local:focal/grafana-k8s-1 from API server
unit-grafana-0: 09:22:27 INFO juju.downloader downloading from local:focal/grafana-k8s-1
unit-grafana-0: 09:22:27 INFO juju.downloader download complete ("local:focal/grafana-k8s-1")
unit-grafana-0: 09:22:27 INFO juju.downloader download verified ("local:focal/grafana-k8s-1")
unit-grafana-0: 09:22:34 INFO juju.worker.uniter hooks are retried true
unit-grafana-0: 09:22:34 INFO juju.worker.uniter found queued "install" hook
unit-grafana-0: 09:22:35 INFO unit.grafana/0.juju-log Running legacy hooks/install.
unit-grafana-0: 09:22:35 INFO unit.grafana/0.juju-log Successfully patched the Kubernetes service!
unit-grafana-0: 09:22:35 INFO juju.worker.uniter.operation ran "install" hook (via hook dispatching script: dispatch)
unit-grafana-0: 09:22:36 INFO juju.worker.uniter.operation ran "grafana-relation-created" hook (via hook dispatching script: dispatch)
unit-grafana-0: 09:22:36 INFO juju.worker.uniter found queued "leader-elected" hook
unit-grafana-0: 09:22:37 INFO juju.worker.uniter.operation ran "leader-elected" hook (via hook dispatching script: dispatch)
unit-grafana-0: 09:22:38 WARNING unit.grafana/0.juju-log Could not read configuration from the Grafana workload container: not-found - stat /etc/grafana/grafana-config.ini: no such file or directory
unit-grafana-0: 09:22:38 INFO unit.grafana/0.juju-log Updated Grafana's base configuration
unit-grafana-0: 09:22:38 WARNING unit.grafana/0.juju-log Could not read configuration from the Grafana workload container: not-found - stat /etc/grafana/provisioning/datasources/datasources.yaml: no such file or directory
unit-grafana-0: 09:22:38 INFO unit.grafana/0.juju-log Updated Grafana's datasource configuration
unit-grafana-0: 09:22:38 INFO unit.grafana/0.juju-log reqs=ResourceRequirements(limits={}, requests={'cpu': '0.25', 'memory': '200Mi'}), templated=ResourceRequirements(limits=None, requests=None), actual=ResourceRequirements(limits=None, requests=None)
unit-grafana-0: 09:22:38 WARNING unit.grafana/0.juju-log Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7072d727c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/health
unit-grafana-0: 09:22:38 WARNING unit.grafana/0.juju-log Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7072d72f40>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/health
unit-grafana-0: 09:22:38 WARNING unit.grafana/0.juju-log Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7072d770d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/health
unit-grafana-0: 09:22:38 INFO juju.worker.uniter.operation ran "grafana-pebble-ready" hook (via hook dispatching script: dispatch)
unit-grafana-0: 09:22:39 INFO juju.worker.uniter.operation ran "litestream-pebble-ready" hook (via hook dispatching script: dispatch)
unit-grafana-0: 09:22:40 INFO juju.worker.uniter.operation ran "database-storage-attached" hook (via hook dispatching script: dispatch)
unit-grafana-0: 09:22:40 INFO unit.grafana/0.juju-log reqs=ResourceRequirements(limits={}, requests={'cpu': '0.25', 'memory': '200Mi'}), templated=ResourceRequirements(limits=None, requests=None), actual=ResourceRequirements(limits=None, requests=None)
unit-grafana-0: 09:22:41 INFO unit.grafana/0.juju-log Restarted replication
unit-grafana-0: 09:22:41 INFO unit.grafana/0.juju-log Kubernetes resources for app 'grafana', container 'grafana' patched successfully: ResourceRequirements(limits={}, requests={'cpu': '0.25', 'memory': '200Mi'})
unit-grafana-0: 09:22:42 INFO juju.worker.caasunitterminationworker terminating due to SIGTERM
unit-grafana-0: 09:22:42 INFO juju.worker.uniter.operation ran "config-changed" hook (via hook dispatching script: dispatch)
unit-grafana-0: 09:22:42 INFO juju.worker.uniter found queued "start" hook
unit-grafana-0: 09:22:42 INFO unit.grafana/0.juju-log Running legacy hooks/start.
unit-grafana-0: 09:22:43 INFO juju.worker.uniter.operation ran "start" hook (via hook dispatching script: dispatch)
unit-grafana-0: 09:22:44 INFO juju.worker.uniter.operation ran "stop" hook (via hook dispatching script: dispatch)
unit-grafana-0: 09:22:44 INFO juju.worker.uniter unit "grafana/0" shutting down: agent should be terminated
unit-grafana-0: 09:22:51 INFO juju.cmd running containerAgent [2.9.31 93e5d53b99a0fc4e5294972a6c3bd3950defc0d1 gc go1.18.2]
unit-grafana-0: 09:22:51 INFO juju.cmd.containeragent.unit start "unit"
unit-grafana-0: 09:22:51 INFO juju.worker.upgrade [...]

2022-08-30 11:41 UTC, simskij approved these changes

2022-08-30 18:18 UTC, merged

2022-09-01 14:07 UTC, sed-i commented
Could you please update the testing instructions with how to manually verify that the replication is not split?
Iirc @simskij was sql-ing in a /etc/grafana/.. db file.

2022-09-01 19:47 UTC, rbarry82 commented
The testing instructions are really "interact with the primary, remove that unit, make sure whatever it fails over it is ok and it continues to propagate".

To manually check, exec into the `grafana` container and `sqlite3 /var/lib/grafana/grafana.db`. Do some stuff on the primary, look at the tables on the followers, make sure they get changes.

Watching the container logs from the `litestream` container will also show you pretty complete output.