Add support for unit ingresses to GrafanaSourceProvider
canonical/grafana-k8s-operator pull request #85
Opened 2022-03-25 06:18 UTC by rbarry82

## Issue
Previously, `GrafanaSourceProvider` only supported connecting directly
to the root URL, so some source (let's say Prometheus) was no longer
accessible once ingress was enabled.

## Solution
A new argument was added to the constructor to allow specifying `source_uri`,
which will be used. If both `source_uri` and `source_port` are specified, a warning
will be emitted. If no scheme is set (such as `http://`), a warning will be emitted, and
the scheme added, so it is clear whether HTTP, HTTPS, or something else should
be used.

## Context
None.

## Testing Instructions
Enable ingress for Prometheus. Instantiate the Provider with the ingress path. Ensure
that it's usable from Grafana. 

Since the Provider Charm is aware of whether or not subpath routing needs to be used
if an ingress is set, even if it's an in-model connection, the Providing charm decides
whether or not to set this argument based on context. A PR is available for Prometheus

## Release Notes
Add support for unit ingresses/source paths  to GrafanaSourceProvider

2022-03-25 06:56 UTC, mmanciop requested changes
Overall looks good, very minor changes seem needed.

2022-03-25 06:56 UTC, mmanciop commented on lib/charms/grafana_k8s/v0/grafana_source.py
> +    `source_uri`: ""
This seems to need more documentation here to explain for which use-cases it is for.

2022-03-25 06:56 UTC, mmanciop commented on lib/charms/grafana_k8s/v0/grafana_source.py
> +        if source_uri and not re.match(r"^\w+://", source_uri):
I like!

2022-03-25 06:56 UTC, mmanciop commented on lib/charms/grafana_k8s/v0/grafana_source.py
> +            source_uri: an optional source uri which can be used if ingress for
It should state that, if not falsy, it overrides the `source_port` argument.

2022-03-25 06:56 UTC, mmanciop commented on lib/charms/grafana_k8s/v0/grafana_source.py
> +                print("ELSE")
This needs to go :-)

2022-03-25 06:57 UTC, mmanciop commented
I hope later today I can try integrate it in `prometheus-k8s`

2022-03-25 10:37 UTC, mmanciop commented
I think the `refresh_event` pattern really did not age well :-(

For Prometheus, we have multiple events when to trigger: When Pebble comes up, and when the ingress changes. So, now I am creating a custom event source for Prometheus just to tell the Grafana source when to store the data in the relation and that is not great. IMO we should just always put the data passed in the constructor in the relation.

2022-03-25 16:50 UTC, mmanciop commented on lib/charms/grafana_k8s/v0/grafana_source.py
> +    `source_uri`: ""
+1

2022-03-25 16:52 UTC, mmanciop commented on lib/charms/grafana_k8s/v0/grafana_source.py
> +        source_uri: Optional[str] = "",
Let's get rid of these defaults, they work for just ONE charm :-)

2022-03-25 20:35 UTC, rbarry82 commented on lib/charms/grafana_k8s/v0/grafana_source.py
> +    `source_uri`: ""
That's actually why [we warn if there's no scheme and add a default](https://github.com/canonical/grafana-k8s-operator/pull/85/files#diff-7ed482b6184969c9603036d352837ddec840d76473e57a583c8b3c5bc49f4cbeR382), but point taken.

2022-03-25 20:42 UTC, rbarry82 commented on lib/charms/grafana_k8s/v0/grafana_source.py
> +                "`source_uri` as the address."
No, it should not be. This is setting attributes in the constructor, which _is_ the action taken, as those are looked up later.

While it would be equally possible to move this message to that function, it's private, would get logged every time `refresh_event` fired, and it would not be obvious from the log where/why to resolve it.

2022-03-25 20:47 UTC, rbarry82 commented on tests/unit/test_source_consumer.py
> +        self.assertEqual(self.harness.charm._stored.source_events, 2)
Pretty much everywhere, in every test, yes, because harness is not always idempotent.

2022-03-25 20:49 UTC, rbarry82 commented on tests/unit/test_source_consumer.py
> +    def test_consumer_notifies_on_new_sources_with_url_without_path(self):
There are no subtests anywhere in the Grafana charm, and they're intentionally avoided until Harness is feature-complete.

2022-03-26 10:35 UTC, mmanciop submitted a review, later dismissed

2022-03-26 10:38 UTC, mmanciop approved these changes
LGTM now. I took the risk of removing the non-sensical default values related with Prometheus, they seem like huge footguns that we should not have.

2022-03-26 10:53 UTC, mmanciop commented
Waiting for the itest to go green, when I'll squash&merge, and ship the lib

2022-03-26 10:59 UTC, mmanciop requested changes
Bug to troubleshoot, see https://github.com/canonical/grafana-k8s-operator/pull/85#issuecomment-1079661302

2022-03-26 11:14 UTC, mmanciop approved these changes
Evidence seems pretty conclusive that the bug lurks somewhere in `prometheus-k8s` or the `ingress` library of `trafik-k8s`.

2022-03-26 13:04 UTC, mmanciop commented on lib/charms/grafana_k8s/v0/grafana_source.py
> +        source_type: str,
The change of order broke the itests, hence bab99df1328d145e091bd4de31a11c9484052f12.

But given that the only charms that use the `GrafanaSourceProvider` are ours, so be it.

2022-03-26 13:57 UTC, merged