Use `promql-transform` to inject label matchers
canonical/grafana-k8s-operator pull request #91
Opened 2022-04-05 04:31 UTC by rbarry82

## Issue
Add `promql-transform` to Grafana's metadata.yaml, and the
`grafana_dashboard` library. The adaptation of the methods differs
slightly from other cases since single, bare expressions will
be passed rather than groups inside alerts, and Grafana dashboards
may include variables and negatives which are not generally used
in alerts.

## Solution

In `GrafanaDashboardConsumer`, pass the topology, transformer, and
dashboard content to a new method. This method iterates over panels,
examines expressions, and makes necessary substitutions for
`promql-transform` to parse them, which are then reversed after
injection (re-adding `-` for negative values, re-adding variable
content inside range selectors).

Add reasonably complex unit tests to cover these cases, as well as
bare `promql-transform`

## Testing Instructions
Import a dashboard from the Grafana marketplace into a charm or `cos-config` (alternatively, take an unmodified, existing dashboard). Relate it to Grafana and ensure that labels are present.

## Release Notes
Inject topology labels into expressions.

Closes #51

2022-04-05 07:36 UTC, simskij requested changes

2022-04-05 07:36 UTC, simskij commented on lib/charms/grafana_k8s/v0/grafana_dashboard.py
> +    return json.dumps(dict_content)
This needs some love in terms of code extraction to make it grokable. With that said, I think this should go into promql-transformer rather than into the charm code.

2022-04-06 14:47 UTC, sed-i approved these changes

2022-04-06 17:22 UTC, rbarry82 commented on lib/charms/grafana_k8s/v0/grafana_dashboard.py
> +        topology: a dict containing topology values
Since they only come from inside this library, which does not (and has not) ever set that prefix, the existing unit tests pretty much cover it.

If it's ever changed, one would be needed/wanted.

2022-04-22 10:01 UTC, balbirthomas commented on lib/charms/grafana_k8s/v0/grafana_dashboard.py
> +    """Inject Juju topology into panel expressions via PromqlTransformer.
The docstring summary line for `_inject_labels()` and `_modify_panel` are identical i.e "Inject Juju topology into panel expressions via PromqlTransformer". Are these methods really doing identical things or is this a copy and paste error ?

2022-04-26 14:50 UTC, rbarry82 commented on lib/charms/grafana_k8s/v0/grafana_dashboard.py
> +    `templating` is used elsewhere in this library, but the structure is not rigid. It is
The lines immediately above this have an example of what the JSON looks like, including a `templating` key and a `targets` key.

2022-04-26 14:51 UTC, rbarry82 commented on lib/charms/grafana_k8s/v0/grafana_dashboard.py
> +    interface, so we add placeholders (as `5y`, since it must parse, but a dashboard looking for
This is a hint for developers who are reading the function for what it does (and why it substitutes), not an indication that end-users need to do anything. They do not.

2022-04-26 14:53 UTC, rbarry82 commented on lib/charms/grafana_k8s/v0/grafana_dashboard.py
> +    """Inject Juju topology into panel expressions via PromqlTransformer.
It is neither. Both methods _do_ inject Juju topology into panel expressions. The difference is in the data passed to each (either an individual panel or a complete dashboard), which is clearly given in `Args:` in the docstrings.

2022-04-27 05:06 UTC, dstathis reviewed
You need to update CONTRIBUTING.md to have the new resource in the deploy command.

2022-04-27 06:40 UTC, rbarry82 commented on .github/workflows/pull-requests.yaml
> +        juju-channel: 2.9/edge
Once 2.9.29 lands, though `latest` is on 3.0 now, so it'll take a lot of testing.

I'll add a comment. Considering the comment that was just removed, I'm not sure we'll remember it without a nagbot, though

2022-04-27 06:40 UTC, rbarry82 commented on metadata.yaml
> +    filename: promql-transform-arm64
I didn't. It should definitely go into `.gitignore`.

2022-04-27 07:06 UTC, rbarry82 commented
> You need to update CONTRIBUTING.md to have the new resource in the deploy command.

Done

2022-05-10 10:05 UTC, simskij reviewed
Can't hit approve until tests are passing, but in general this looks reasonable to me.

2022-05-10 10:58 UTC, rbarry82 commented on lib/charms/grafana_k8s/v0/grafana_dashboard.py
> +    """Inject Juju topology into panel expressions via PromqlTransformer.
I'm against this mostly because it is not actually modifying a "complete" dashboard, but operating on a subset.

The downside of this is that an understanding of how Grafana uses terms to describe pieces of dashboards is needed for this to seem "extra" meaningful. The upside to this is that nominal authors will be aware of that terminology and be able to distinguish the difference between what we are modifying.

2022-06-07 12:08 UTC, simskij approved these changes
We should move PromqlTransformer to observability-libs. Fine with merging this as-is as a first step though.

2022-06-29 13:10 UTC, Abuelodelanada approved these changes

2022-06-29 13:10 UTC, Abuelodelanada commented on .github/workflows/pull-requests.yaml
> +        juju-channel: 2.9/edge # FIXME: Back to stable once 2.9.29 releases
Is this still valid? `2.9.32` was released this week.

2022-09-20 23:53 UTC, merged